In [102]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [93]:
np.random.seed(42)
num_records=1000
location_list=['Dubai Marina', 'Downtown Dubai', 'JVC', 'Abu Dhabi Reem Island', 'Sharjah Al Majaz']

property_id=list(range(1,1001))
location=np.random.choice(location_list,num_records)
bedrooms=np.random.randint(1,6,num_records)

area=(bedrooms*750)+np.random.randint(0,100,1000)
price_per_sqft_map={
    'Dubai Marina':2500,
    'Downtown Dubai':3000,
    'JVC':1100,
    'Abu Dhabi Reem Island':1400,
    'Sharjah Al Majaz':800
}
df=pd.DataFrame(
    {
        'Property_ID':property_id,
        'Location':location,
        'Bedrooms':bedrooms,
        'Area(Sqft)':area
    }
)
df['price']=df['Area(Sqft)']*df['Location'].map(price_per_sqft_map)

In [94]:
df

     Property_ID               Location  Bedrooms  Area(Sqft)    price
0              1  Abu Dhabi Reem Island         4        3091  4327400
1              2       Sharjah Al Majaz         4        3070  2456000
2              3                    JVC         4        3031  3334100
3              4       Sharjah Al Majaz         4        3010  2408000
4              5       Sharjah Al Majaz         5        3759  3007200
..           ...                    ...       ...         ...      ...
995          996         Downtown Dubai         1         810  2430000
996          997           Dubai Marina         5        3785  9462500
997          998           Dubai Marina         1         789  1972500
998          999  Abu Dhabi Reem Island         5        3830  5362000
999         1000                    JVC         3        2279  2506900

[1000 rows x 5 columns]

In [95]:
df1=pd.get_dummies(df['Location'])
df=pd.concat([df,df1],axis=1)

In [96]:
df=df.drop(['Location'],axis=1)

In [97]:
df

,Property_ID,Bedrooms,Area(Sqft),price,Abu Dhabi Reem Island,Downtown Dubai,Dubai Marina,JVC,Sharjah Al Majaz
0,1,4,3091,4327400,True,False,False,False,False
1,2,4,3070,2456000,False,False,False,False,True
2,3,4,3031,3334100,False,False,False,True,False
3,4,4,3010,2408000,False,False,False,False,True
4,5,5,3759,3007200,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
995,996,1,810,2430000,False,True,False,False,False
996,997,5,3785,9462500,False,False,True,False,False
997,998,1,789,1972500,False,False,True,False,False
998,999,5,3830,5362000,True,False,False,False,False
999,1000,3,2279,2506900,False,False,False,True,False

In [98]:
x=df.drop(['Property_ID','price'],axis=1)
y=df['price']

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [100]:
model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

In [103]:
y_pred=model.predict(x_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9997160925352779
10251.485

In [104]:
import joblib

In [106]:
joblib.dump(model,'uae_real_estate_model.pkl')
joblib.dump(list(x.columns),'model_columns.pkl')

['model_columns.pkl']